language: node_js

node_js:
  - "lts/*"

services:
  - docker

cache: false

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  - "npm install ep_test_line_attrib"

before_script:
  - "tests/frontend/travis/sauce_tunnel.sh"

script:
  - "tests/frontend/travis/runner.sh"

addons:
  sauce_connect:
    username: "etherpad"
  jwt:
    secure: "RVrOl1MyxzGaB/L6AWmcj8XWik4rN+tj+R+oiW363us2svI3Mq/uz9q+SmtpfZYBIjeUYXIolL90TukqcEocPNlz/6H9PDPvw8CiDukXBNrgqpX443+bOPs9949ABBY5bRrJJux/VJ25EEr5Zwu4+c6ecwTJzkzDlz9eHXSzWIvRJK1owhCRpAat2eikQlR23Co1BRfGL8O+UHtwbhCrTEWYwwufSMvkV74aMXMNCqdj9K4LRawTMD0wdSqal1dTLyqp/LjqBxiQtnzUiqh2o1dUzfR+m1W1iX66zzuLmCohXW7gLJuvVL0tO4vM4PbfQ2aQciF0Ww09K/sypIPOd5PosfhYqfkgwM6ex2mlT9+3CRi6apd3e1Izh7+YrO7JiOs78HHoEfUwljAtaB9nAvXiStTSVK9pswkAn1XX/goh8E4wr3x5SmI7K+GBaJWQxHgS1+Qxv2BFnAisBIflO9rR617xB9uJvUdKUh0n5OiuZ0YUIriISF1nlNDQmSZf1bZxgvtlFNKTvl+XhUm+rMc/WluYwJAIYh1pwaoJ7KJYDnh2BqWszjcE21POScQ7ZTU6sHrCSrEhcf2ZxupmoHQ0RNRIwly+XLKe/FO2UlQpgcouIz4LiqbviG5HWEqTgS/BKwj+iN71mhHVre2g8mZsMx6615bunh2PoaacWJE="

jobs:
  include:
    - name: "Run the Backend tests"
      install:
        - "mkdir ep_webrtc"
        - "mv !(ep_webrtc) ep_webrtc"
        - "git clone https://github.com/ether/etherpad-lite.git etherpad"
        - "cd etherpad"
        - "mkdir node_modules"
        - "mv ../ep_webrtc node_modules"
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
        - "npm install ep_test_line_attrib"
        - "cd src && npm install && cd -"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Test the Frontend"
      install:
        - "mkdir ep_webrtc"
        - "mv !(ep_webrtc) ep_webrtc"
        - "git clone https://github.com/ether/etherpad-lite.git etherpad"
        - "cd etherpad"
        - "mkdir node_modules"
        - "mv ../ep_webrtc node_modules"
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
        - "npm install ep_test_line_attrib"
      script:
        - "tests/frontend/travis/runner.sh"

notifications:
  irc:
    channels:
      - "irc.freenode.org#etherpad-lite-dev"
